/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as FounderDebugRouteImport } from './routes/founder-debug'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTranscriptStreamRouteImport } from './routes/api/public/transcript-stream'
import { Route as ApiPublicProductProbeRouteImport } from './routes/api/public/product-probe'
import { Route as ApiPublicAsrProbeProgressiveRouteImport } from './routes/api/public/asr-probe-progressive'
import { Route as ApiPublicAsrProbeRouteImport } from './routes/api/public/asr-probe'
import { Route as ApiPublicAsrBenchmarkRunRouteImport } from './routes/api/public/asr-benchmark-run'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderDebugRoute = FounderDebugRouteImport.update({
  id: '/founder-debug',
  path: '/founder-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscriptStreamRoute =
  ApiPublicTranscriptStreamRouteImport.update({
    id: '/api/public/transcript-stream',
    path: '/api/public/transcript-stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProductProbeRoute = ApiPublicProductProbeRouteImport.update({
  id: '/api/public/product-probe',
  path: '/api/public/product-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsrProbeProgressiveRoute =
  ApiPublicAsrProbeProgressiveRouteImport.update({
    id: '/api/public/asr-probe-progressive',
    path: '/api/public/asr-probe-progressive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAsrProbeRoute = ApiPublicAsrProbeRouteImport.update({
  id: '/api/public/asr-probe',
  path: '/api/public/asr-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsrBenchmarkRunRoute =
  ApiPublicAsrBenchmarkRunRouteImport.update({
    id: '/api/public/asr-benchmark-run',
    path: '/api/public/asr-benchmark-run',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/founder': typeof FounderRoute
  '/founder-debug': typeof FounderDebugRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/asr-benchmark-run': typeof ApiPublicAsrBenchmarkRunRoute
  '/api/public/asr-probe': typeof ApiPublicAsrProbeRoute
  '/api/public/asr-probe-progressive': typeof ApiPublicAsrProbeProgressiveRoute
  '/api/public/product-probe': typeof ApiPublicProductProbeRoute
  '/api/public/transcript-stream': typeof ApiPublicTranscriptStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/founder': typeof FounderRoute
  '/founder-debug': typeof FounderDebugRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/asr-benchmark-run': typeof ApiPublicAsrBenchmarkRunRoute
  '/api/public/asr-probe': typeof ApiPublicAsrProbeRoute
  '/api/public/asr-probe-progressive': typeof ApiPublicAsrProbeProgressiveRoute
  '/api/public/product-probe': typeof ApiPublicProductProbeRoute
  '/api/public/transcript-stream': typeof ApiPublicTranscriptStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/founder': typeof FounderRoute
  '/founder-debug': typeof FounderDebugRoute
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/asr-benchmark-run': typeof ApiPublicAsrBenchmarkRunRoute
  '/api/public/asr-probe': typeof ApiPublicAsrProbeRoute
  '/api/public/asr-probe-progressive': typeof ApiPublicAsrProbeProgressiveRoute
  '/api/public/product-probe': typeof ApiPublicProductProbeRoute
  '/api/public/transcript-stream': typeof ApiPublicTranscriptStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/founder'
    | '/founder-debug'
    | '/saved'
    | '/sitemap.xml'
    | '/api/public/asr-benchmark-run'
    | '/api/public/asr-probe'
    | '/api/public/asr-probe-progressive'
    | '/api/public/product-probe'
    | '/api/public/transcript-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/founder'
    | '/founder-debug'
    | '/saved'
    | '/sitemap.xml'
    | '/api/public/asr-benchmark-run'
    | '/api/public/asr-probe'
    | '/api/public/asr-probe-progressive'
    | '/api/public/product-probe'
    | '/api/public/transcript-stream'
  id:
    | '__root__'
    | '/'
    | '/founder'
    | '/founder-debug'
    | '/saved'
    | '/sitemap.xml'
    | '/api/public/asr-benchmark-run'
    | '/api/public/asr-probe'
    | '/api/public/asr-probe-progressive'
    | '/api/public/product-probe'
    | '/api/public/transcript-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FounderRoute: typeof FounderRoute
  FounderDebugRoute: typeof FounderDebugRoute
  SavedRoute: typeof SavedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicAsrBenchmarkRunRoute: typeof ApiPublicAsrBenchmarkRunRoute
  ApiPublicAsrProbeRoute: typeof ApiPublicAsrProbeRoute
  ApiPublicAsrProbeProgressiveRoute: typeof ApiPublicAsrProbeProgressiveRoute
  ApiPublicProductProbeRoute: typeof ApiPublicProductProbeRoute
  ApiPublicTranscriptStreamRoute: typeof ApiPublicTranscriptStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-debug': {
      id: '/founder-debug'
      path: '/founder-debug'
      fullPath: '/founder-debug'
      preLoaderRoute: typeof FounderDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcript-stream': {
      id: '/api/public/transcript-stream'
      path: '/api/public/transcript-stream'
      fullPath: '/api/public/transcript-stream'
      preLoaderRoute: typeof ApiPublicTranscriptStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-probe': {
      id: '/api/public/product-probe'
      path: '/api/public/product-probe'
      fullPath: '/api/public/product-probe'
      preLoaderRoute: typeof ApiPublicProductProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asr-probe-progressive': {
      id: '/api/public/asr-probe-progressive'
      path: '/api/public/asr-probe-progressive'
      fullPath: '/api/public/asr-probe-progressive'
      preLoaderRoute: typeof ApiPublicAsrProbeProgressiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asr-probe': {
      id: '/api/public/asr-probe'
      path: '/api/public/asr-probe'
      fullPath: '/api/public/asr-probe'
      preLoaderRoute: typeof ApiPublicAsrProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asr-benchmark-run': {
      id: '/api/public/asr-benchmark-run'
      path: '/api/public/asr-benchmark-run'
      fullPath: '/api/public/asr-benchmark-run'
      preLoaderRoute: typeof ApiPublicAsrBenchmarkRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FounderRoute: FounderRoute,
  FounderDebugRoute: FounderDebugRoute,
  SavedRoute: SavedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicAsrBenchmarkRunRoute: ApiPublicAsrBenchmarkRunRoute,
  ApiPublicAsrProbeRoute: ApiPublicAsrProbeRoute,
  ApiPublicAsrProbeProgressiveRoute: ApiPublicAsrProbeProgressiveRoute,
  ApiPublicProductProbeRoute: ApiPublicProductProbeRoute,
  ApiPublicTranscriptStreamRoute: ApiPublicTranscriptStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
