BEGIN;
INSERT INTO public.benchmark_videos (video_id, youtube_url, title, category, difficulty, language, active) VALUES
  ('iCvmsMzlF7o','https://youtu.be/iCvmsMzlF7o?si=6Geq4pdABvgQ0KOm','Brené Brown – The Power of Vulnerability','TED Talk','easy','en',true),
  ('qp0HIF3SfI4','https://youtu.be/qp0HIF3SfI4?si=yEiX8bt9soa6Dr3i','Simon Sinek – How Great Leaders Inspire Action','TED Talk','easy','en',true),
  ('NFubmeHDtII','https://youtu.be/NFubmeHDtII?si=FXzqGbEwYPSoKPeC','Ken Robinson – Do Schools Kill Creativity?','TED Talk','easy','en',true),
  ('Ks-_Mh1QhMc','https://youtu.be/Ks-_Mh1QhMc?si=snSGM8i3-M2oAQwK','Amy Cuddy – Your Body Language Shapes Who You Are','TED Talk','easy','en',true),
  ('Drj0cZTBhUI','https://youtu.be/Drj0cZTBhUI?si=dujzwDYHYtyxhoum','Chimamanda Ngozi Adichie – The Danger of a Single Story','TED Talk','medium','en',true),
  ('arj7oStGLkU','https://youtu.be/arj7oStGLkU?si=NqkrpeQPF-feK4-U','Tim Urban – Inside the Mind of a Master Procrastinator','TED Talk','easy','en',true),
  ('8KkKuTCFvzI','https://www.youtube.com/watch?v=8KkKuTCFvzI','Robert Waldinger – What Makes a Good Life?','TED Talk','easy','en',true),
  ('4q1dgn_C0AU','https://youtu.be/4q1dgn_C0AU?si=HrGAwekK_38CoMkx','Dan Gilbert – The Surprising Science of Happiness','TED Talk','medium','en',true),
  ('eIho2S0ZahI','https://www.youtube.com/watch?v=eIho2S0ZahI','Julian Treasure – How to Speak So People Want to Listen','TED Talk','easy','en',true),
  ('rrkrvAUbU9Y','https://youtu.be/rrkrvAUbU9Y?si=sq7zb0tvZ7TjsLum','Dan Pink – The Puzzle of Motivation','TED Talk','medium','en',true),
  ('nzj7Wg4DAbs','https://youtu.be/nzj7Wg4DAbs?si=cs61vR_xjyg8_g1w','Yuval Noah Harari – Why Humans Run the World','TED Talk','hard','en',true),
  ('dBYUn-FEscc','https://youtu.be/dBYUn-FEscc?si=7WozIHTJsJwrgcpd','Andrew Solomon – Depression the Secret We Share','TED Talk','medium','en',true),
  ('aXZPJ8yGbwU','https://youtu.be/aXZPJ8yGbwU?si=J5sjxD8KcDdF7ZKm','Malala Yousafzai – My Fight for Education','TED Talk','easy','en',true),
  ('JaF-fq2Zn7I','https://youtu.be/JaF-fq2Zn7I?si=rqXc5zoDwFpR2OO6','Bill Gates – Innovating to Zero','TED Talk','medium','en',true),
  ('hVimVzgtD6w','https://youtu.be/hVimVzgtD6w?si=2VwXPB_posZ6sI7Q','Hans Rosling – The Best Stats You''ve Ever Seen','TED Talk','medium','en',true),
  ('c0KYU2j0TM4','https://youtu.be/c0KYU2j0TM4?si=ueprROUHI7kQLDkJ','Susan Cain – The Power of Introverts','TED Talk','easy','en',true),
  ('fLJsdqxnZb0','https://youtu.be/fLJsdqxnZb0?si=5MQJ8EtaXS06Fear','Shawn Achor – The Happy Secret to Better Work','TED Talk','easy','en',true),
  ('86x-u-tz0MA','https://youtu.be/86x-u-tz0MA?si=Dpsvf8bPquqYKJpP','Elizabeth Gilbert – Your Elusive Creative Genius','TED Talk','easy','en',true),
  ('7pPqRNk2Qhw','https://youtu.be/7pPqRNk2Qhw?si=iR3RFqLIrxsc6jsn','James Veitch – This is What Happens When You Reply to Spam','TED Talk','easy','en',true),
  ('H14bBuluwB8','https://youtu.be/H14bBuluwB8?si=mfoNrOE8H8th4FwP','Angela Duckworth – Grit: The Power of Passion','TED Talk','easy','en',true),
  ('AdKUJxjn-R8','https://youtu.be/AdKUJxjn-R8?si=i8q3LJSg4OFHbOvO','BJ Fogg – Forget Big Change, Start With a Tiny Habit','TED Talk','medium','en',true),
  ('fxbCHn6gE3U','https://youtu.be/fxbCHn6gE3U?si=xFOQArgZNfYu3KRA','Adam Grant – The Surprising Habits of Original Thinkers','TED Talk','medium','en',true),
  ('R1vskiVDwl4','https://youtu.be/R1vskiVDwl4?si=LY8x-h6YDphv6FYu','Celeste Headlee – 10 Ways to Have a Better Conversation','TED Talk','easy','en',true),
  ('4c1lqFXHvqI','https://youtu.be/4c1lqFXHvqI?si=GRfr6t4mG6zZQaLK','David Eagleman – Can We Create New Senses for Humans?','TED Talk','hard','en',true),
  ('ydKcaIE6O1k','https://youtu.be/ydKcaIE6O1k?si=l6pZFkI2Iv0VmVGT','Rutger Bregman – Poverty Isn''t a Lack of Character','TED Talk','medium','en',true),
  ('kQ3Ih7Tdx2I','https://youtu.be/kQ3Ih7Tdx2I?si=3GeC15vokhlneJt1','NOS Journaal – 8 uur hoofduitzending','NPO/NOS','medium','nl',true),
  ('FBy1aM4HprE','https://youtu.be/FBy1aM4HprE?si=arEola4Q9KFsh3LY','Nieuwsuur – Politieke analyse','NPO/NOS','hard','nl',true),
  ('p2SJYaRXAfU','https://youtu.be/p2SJYaRXAfU?si=j3flpTOkdRlgOtTw','VPRO Tegenlicht – De digitale samenleving','NPO/NOS','hard','nl',true),
  ('8dlwpwZdGzg','https://www.youtube.com/watch?v=8dlwpwZdGzg','Zo machtig is India','NPO/NOS','medium','nl',true),
  ('OGVlDbsHQKs','https://www.youtube.com/watch?v=OGVlDbsHQKs&list=PLZ0df6wQ5oO8WKNZ6W4kzvaMIkRVxGl3E','Universiteit van Nederland – Why sea foam is full of poison','NPO/NOS','medium','nl',true),
  ('QMhZrMIWPbg','https://www.youtube.com/watch?v=QMhZrMIWPbg','Zondag met Lubach – Klimaatakkoord uitgelegd','NPO/NOS','easy','nl',true),
  ('PJjuuyO0ap0','https://www.youtube.com/watch?v=PJjuuyO0ap0','Zondag met Lubach – Stikstofcrisis','NPO/NOS','medium','nl',true),
  ('bg-SYZ8sBow','https://youtu.be/bg-SYZ8sBow?si=w8bhCsL7Y8N9V-X1','VPRO Tegenlicht – Toekomst van internet','NPO/NOS','hard','nl',true),
  ('tAQfCt6IpHA','https://youtu.be/tAQfCt6IpHA?si=r8Ry7xh99Hp-nAax','De Kennis van Nu – Klimaatwetenschap','NPO/NOS','medium','nl',true),
  ('TtSnUC3ci2E','https://youtu.be/TtSnUC3ci2E?si=BRLKACzbxh1ZzYoy','EenVandaag – Woningcrisis reportage','NPO/NOS','medium','nl',true),
  ('-2zj9qoWXps','https://www.youtube.com/watch?v=-2zj9qoWXps','NOS op 3 – Hoe werkt de beurs?','NPO/NOS','easy','nl',true),
  ('Z_6IuOaDVHg','https://youtu.be/Z_6IuOaDVHg?si=dssSwKMEM9S0BV_V','Andere Tijden – WOII documentaire','NPO/NOS','medium','nl',true)
ON CONFLICT (video_id) DO UPDATE SET youtube_url=EXCLUDED.youtube_url, title=EXCLUDED.title, category=EXCLUDED.category, difficulty=EXCLUDED.difficulty, language=EXCLUDED.language, active=true, updated_at=now();
UPDATE public.benchmark_videos SET active=false, updated_at=now() WHERE video_id NOT IN ('iCvmsMzlF7o','qp0HIF3SfI4','NFubmeHDtII','Ks-_Mh1QhMc','Drj0cZTBhUI','arj7oStGLkU','8KkKuTCFvzI','4q1dgn_C0AU','eIho2S0ZahI','rrkrvAUbU9Y','nzj7Wg4DAbs','dBYUn-FEscc','aXZPJ8yGbwU','JaF-fq2Zn7I','hVimVzgtD6w','c0KYU2j0TM4','fLJsdqxnZb0','86x-u-tz0MA','7pPqRNk2Qhw','H14bBuluwB8','AdKUJxjn-R8','fxbCHn6gE3U','R1vskiVDwl4','4c1lqFXHvqI','ydKcaIE6O1k','kQ3Ih7Tdx2I','FBy1aM4HprE','p2SJYaRXAfU','8dlwpwZdGzg','OGVlDbsHQKs','QMhZrMIWPbg','PJjuuyO0ap0','bg-SYZ8sBow','tAQfCt6IpHA','TtSnUC3ci2E','-2zj9qoWXps','Z_6IuOaDVHg');
COMMIT;