INSERT INTO public.curated_videos
 (provider, external_id, url, title, channel, thumbnail_url, duration_sec, language, cefr_level,
  difficulty_score, speaking_speed, words_per_minute, category, topics, summary, has_subtitles,
  quality_score, popularity, is_evergreen, featured_week, status, is_embeddable, validation_status, validated_at, refreshed_at)
VALUES
 ('youtube','Qi2pDrPeDqg','https://www.youtube.com/watch?v=Qi2pDrPeDqg','Nederlands leren: Een dag naar de markt 🧀 | Luisteren & Begrijpen (A1)','Daily Dutch Stories','https://i.ytimg.com/vi/Qi2pDrPeDqg/hqdefault.jpg',335,'nl','A1',1,'slow',164,'Learning Dutch',ARRAY['daily life','shopping'],'A short, slow story about a day at the Dutch market with clear beginner vocabulary.',true,1,1000,true,date_trunc('week',now())::date,'active',true,'ok',now(),now()),
 ('youtube','jzTUo7efsow','https://www.youtube.com/watch?v=jzTUo7efsow','Dutch greetings // Dutch for beginners les 1 (NT2 - A1)','Dutchies to be','https://i.ytimg.com/vi/jzTUo7efsow/hqdefault.jpg',233,'nl','A1',1,'slow',91,'Learning Dutch',ARRAY['greetings','basics'],'First beginner lesson covering Dutch greetings with very clear pronunciation.',true,1,1000,true,date_trunc('week',now())::date,'active',true,'ok',now(),now()),
 ('youtube','BBe9vCH0T7o','https://www.youtube.com/watch?v=BBe9vCH0T7o','Dutch question words // Vraagwoorden (NT2 - A1)','Dutchies to be','https://i.ytimg.com/vi/BBe9vCH0T7o/hqdefault.jpg',621,'nl','A1',1,'slow',99,'Learning Dutch',ARRAY['grammar','questions'],'Beginner lesson on Dutch question words with slow, repeated examples.',true,1,1000,true,date_trunc('week',now())::date,'active',true,'ok',now(),now()),
 ('youtube','ZBHyyYUmj14','https://www.youtube.com/watch?v=ZBHyyYUmj14','Boodschappen doen // Grocery shopping in Dutch (NT2 - A1)','Dutchies to be','https://i.ytimg.com/vi/ZBHyyYUmj14/hqdefault.jpg',642,'nl','A1',1,'normal',125,'Learning Dutch',ARRAY['shopping','daily life'],'Beginner lesson about grocery shopping vocabulary and useful shop phrases.',true,1,1000,true,date_trunc('week',now())::date,'active',true,'ok',now(),now()),
 ('youtube','Y3g2xfcrYUg','https://www.youtube.com/watch?v=Y3g2xfcrYUg','Modale werkwoorden // Dutch modal verbs (NT2 - A1)','Dutchies to be','https://i.ytimg.com/vi/Y3g2xfcrYUg/hqdefault.jpg',660,'nl','A1',1,'normal',115,'Learning Dutch',ARRAY['grammar','verbs'],'Clear beginner explanation of Dutch modal verbs with everyday examples.',true,1,1000,true,date_trunc('week',now())::date,'active',true,'ok',now(),now()),
 ('youtube','icnsu6HBrkE','https://www.youtube.com/watch?v=icnsu6HBrkE','Leer Nederlands met gesprekken | Basisvragen en antwoorden','Easy Dutch Conversations','https://i.ytimg.com/vi/icnsu6HBrkE/hqdefault.jpg',816,'nl','A1',1,'normal',121,'Conversation',ARRAY['conversation','basics'],'Simple Dutch question-and-answer dialogues for absolute beginners, with subtitles.',true,1,1000,true,date_trunc('week',now())::date,'active',true,'ok',now(),now()),
 ('youtube','v_w0q5aXgLQ','https://www.youtube.com/watch?v=v_w0q5aXgLQ','10 real-life Dutch conversations for beginners (A1-A2)','DutchTalks','https://i.ytimg.com/vi/v_w0q5aXgLQ/hqdefault.jpg',1395,'nl','A1',1,'slow',70,'Conversation',ARRAY['conversation','daily life'],'Ten short everyday Dutch conversations spoken slowly for beginners.',true,1,1000,true,date_trunc('week',now())::date,'active',true,'ok',now(),now()),
 ('youtube','jSyrqH_MMOM','https://www.youtube.com/watch?v=jSyrqH_MMOM','100 woorden die je moet weten in Nederland | Super Easy Dutch','Easy Dutch','https://i.ytimg.com/vi/jSyrqH_MMOM/hqdefault.jpg',762,'nl','A1',1,'slow',76,'Daily Life',ARRAY['vocabulary','daily life'],'Street interviews and clear narration teaching 100 essential Dutch words.',true,1,1000,true,date_trunc('week',now())::date,'active',true,'ok',now(),now())
ON CONFLICT DO NOTHING;